### ISSUE TITLE
打包后运行，登录后跳转界面报RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by llh0928** [bailihuiyue/ant-design-pro-vue3#12]
你好，这个工程本地运行正常，登录后跳转界面报RangeError: Maximum call stack size exceeded，刷新地址栏后，路由跳转正常，这是什么原因呢？

**Comment by llh0928** [comment]
@bailihuiyue

**Comment by bailihuiyue** [comment]
你好,请使用pnpm重新安装依赖试试,并没有发现这个问题
