### ISSUE TITLE
使用mockUtils返回的路由会报404

### ISSUE THREAD

**Issue by Qmagician** [bailihuiyue/ant-design-pro-vue3#4]

**Comment by bailihuiyue** [comment]
因为使用动态路由后,页面的渲染是根据路由名称命名的,比如/dashboard/workplace这个路由,项目的views文件夹中就应该包含Workplace.vue,如果找不到,就会渲染成404.vue,如图所示

![微信截图_20220620170053](https://user-images.githubusercontent.com/33573384/174566031-368e57ab-aed5-4546-b2a3-cc7cdd3a0d49.png)

**Comment by Qmagician** [comment]
您好！您的邮件我已经收到！会尽快给您回复！谢谢！
