### ISSUE TITLE
使用tsx组件不加载antd的table组件样式

### ISSUE THREAD

**Issue by quanjialiang** [bailihuiyue/ant-design-pro-vue3#5]
复现操作如下：
1.修改exampleRouterMap.ts路由为/profile/basic的组件路径，由Home.vue改为About.tsx，修改Helloworld组件，添加a-button和a-table组件
![image](https://user-images.githubusercontent.com/26588046/174035445-80c4102e-b0f9-4a27-b22d-1aacc83b2e97.png)
![image](https://user-images.githubusercontent.com/26588046/174034826-6844a5d1-c7d1-437a-ae59-cde06942724e.png)
![image](https://user-images.githubusercontent.com/26588046/174034235-5bc81c94-3512-4e0d-89e4-acf20bf3c2d8.png)

2.登录系统后访问http://localhost:3000/profile/basic
3.刷新页面（刷新是为了防止其他页面加载样式），发现按钮样式正常，表格样式不正常
![image](https://user-images.githubusercontent.com/26588046/174035607-a23bdb2b-b694-4db5-8bd0-aacab33a290b.png)

**Comment by bailihuiyue** [comment]
bug原理:
代码设计时使用了一个可以自动引入组件的插件(vite-plugin-components),因此组件的引入不需要use,等方法,vite插件会自动引入组件的代码和css样式,但是可能这个组件有bug,有的时候css不会自动引入,也许和jsx有关,具体我也没搞清楚,


解决方案1:
vite-plugin-components插件已升级为unplugin-vue-components,并且在vite.config.ts中配置完成,支持vue和jsx文件,理论上重新安装一遍依赖问题就会解决了

解决方案2:
如图
![image](https://user-images.githubusercontent.com/33573384/174568245-f557a524-da57-4f52-b1c3-93fc182db2b2.png)
在components_use.ts中手动引入样式文件即可
并且自动引入组件的插件对jsx无效,只适用于vue文件,jsx需自己引入组件
![image](https://user-images.githubusercontent.com/33573384/174568824-5a6e7858-b72c-4ab5-beae-fc4822db56f0.png)
完成后效果如下:
![image](https://user-images.githubusercontent.com/33573384/174568886-745ede5c-7893-410c-a170-2820e3b7984f.png)
