### ISSUE TITLE
菜单组件onSelect类型检查不通过

### ISSUE THREAD

**Issue by RaghuLiu** [bailihuiyue/ant-design-pro-vue3#7]
![image](https://user-images.githubusercontent.com/39978330/219531469-03433506-d020-4a1e-a651-61d0de681ca1.png)
菜单组件疯狂报这个

**Comment by bailihuiyue** [comment]
这个好像是antv的bug,onSelect是一层层emit到外面的都叫onSelect好像有冲突,给他们改名试试,比如叫onTest,onTest1
