### ISSUE TITLE
开发球

### ISSUE THREAD

**Issue by huoshicang** [bailihuiyue/ant-design-pro-vue3#8]
![image](https://user-images.githubusercontent.com/74391377/236657696-69867244-9b8a-4807-951c-a9d77dad4285.png)
我想运行带开发球的命令，但是提示报错，请问该怎么解决

**Comment by changer-wang** [comment]
npm install -g concurrently 安装依赖

**Comment by bailihuiyue** [comment]
@changer-wang 老哥正解,vite会更新后少写了4个依赖,已修复
